print(8/2)
print(12/3+3)
print(3+6/2)
print(4+2*5)
num=int(input("enter num"))
print("num*1=num")
print(f"{num}*1={num}")
print(f"{num}*2={num*2}")
print(f"{num}*3={num*3}")
print(f"{num}*4={num*4}")
print(f"{num}*5={num*5}")